## Specify the model to use for the main chat
model: ollama_chat/qwen2.5-coder:14b

## Specify a file with aider model settings for unknown models
model-settings-file: .aider.model.settings.yml

## Specify the model to use for commit messages and chat history summarization (default depends on --model)
weak-model: ollama_chat/llama3.1:8b

## Use colors suitable for a dark terminal background (default: False)
dark-mode: true

## Set the markdown code theme (default: default, other options include monokai, solarized-dark, solarized-light, or a Pygments builtin style, see https://pygments.org/styles for available themes)
code-theme: material

## Enable/disable automatic linting after changes (default: True)
auto-lint: false

## Enable/disable auto commit of LLM changes (default: True)
auto-commits: false
