- name: ollama/deepseek-coder-v2:16b
  extra_params:
    num_ctx: 8192

- name: ollama/deepseek-r1:14b
  extra_params:
    num_ctx: 8192

- name: ollama/qwen2.5-coder:14b
  extra_params:
    num_ctx: 8192

- name: ollama/llama3.1:8b
  extra_params:
    num_ctx: 8192
