## Specify the model to use for the main chat
model: openrouter/deepseek/deepseek-r1
# model: anthropic/claude-3-7-sonnet-20250219

## Specify the model to use for editor tasks (default depends on --model)
editor-model: openrouter/deepseek/deepseek-chat
# editor-model: openrouter/anthropic/claude-3.7-sonnet

## Specify a file with aider model settings for unknown models
model-settings-file: .aider.model.settings.yml

## Set the markdown code theme (default: default, other options include monokai, solarized-dark, solarized-light, or a Pygments builtin style, see https://pygments.org/styles for available themes)
code-theme: github-dark

## Enable/disable auto commit of LLM changes (default: True)
auto-commits: false
