# Taps
tap "oven-sh/bun"

# Utilities
brew "rustup"
brew "bat"
brew "btop"
brew "eza"
brew "gnu-sed"
brew "fzf"
brew "fd"
brew "fastfetch"
brew "onefetch"
brew "yazi"
brew "tealdeer"
brew "ripgrep"
brew "starship"
brew "zoxide"
brew "imagemagick"
brew "stow"
brew "delta"
brew "chafa"
brew "inetutils"
brew "ffmpeg"
brew "ollama"
# brew "aichat"
brew "sevenzip"
brew "tectonic"
brew "rename"
brew "wget"

# Dev
brew "gh"
brew "hub"
brew "lazygit"
brew "lazydocker"
brew "tree-sitter", args: ['HEAD']
brew "neovim", args: ['HEAD']
brew "helix"
brew "fnm"
brew "oven-sh/bun/bun"
brew "uv"
brew "go"
brew "luarocks"
brew "tmux"
brew "watchman"
brew "posting"
brew "act"
cask "mockoon"
cask "visual-studio-code"
cask "trae"
cask "zed"
cask "ghostty"
cask "kitty"
cask "bruno"
cask "orbstack"
brew "vercel-cli"
brew "openjdk"
cask "android-studio"
brew "gemini-cli"

# Apps
cask "legcord"
cask "zen-browser"
cask "google-chrome"
cask "spotify"
cask "steam"
cask "whatsapp"
cask "cyberduck"
cask "slack"
cask "raycast"
cask "google-drive"
cask "macpass"
cask "linear-linear"
cask "tailscale-app"
cask "protonvpn"
cask "qutebrowser"

# Fonts
cask "font-iosevka"
cask "font-roboto-mono-nerd-font"
cask "sf-symbols"
# cask "font-hack"
# cask "font-jetbrains-mono"
# cask "font-victor-mono"
# cask "font-fira-code"
# cask "font-aporetic"
# cask "font-roboto-mono"
# cask "font-monaspace"
# cask "font-ibm-plex-mono"
# cask "font-mononoki"
# cask "font-monoid"
# cask "font-open-dyslexic"
# cask "font-departure-mono"
