[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''', "yank" ]

[[mgr.prepend_keymap]]
on   = ["e", "t"]
run  = '''
	shell 'gio trash --empty' --confirm
'''
desc = "Empty the trash"

[[mgr.prepend_keymap]]
on  = "k"
run = "plugin arrow -1"

[[mgr.prepend_keymap]]
on  = "j"
run = "plugin arrow 1"
