theme = "catppuccin_trans"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
